<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "contact".
 *
 * @property integer $id
 * @property string $phone
 * @property string $email
 * @property string $address
 * @property string $address_ru
 * @property string $address_en
 * @property string $link_fb
 * @property string $link_linkedin
 * @property string $link_viber
 * @property string $link_insta
 * @property string $link_mail
 * @property string $mobile_1
 * @property string $mobile_2
 * @property string $mobile_3
 */
class Contact extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'contact';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['phone', 'email', 'address', 'address_ru', 'address_en', 'link_fb', 'link_linkedin', 'link_viber', 'link_mail', 'link_insta', 'mobile_1', 'mobile_2', 'mobile_3'], 'string', 'max' => 255],
            [['phone', 'email', 'address', 'address_ru', 'address_en'], 'required'],
            [['email'], 'email'],
        ];
    }


    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            $cache = Yii::$app->cache;
            $key = "update_time";
            $cache->set($key, time());



            return true;
        }
        return false;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'phone' => 'Телефон',
            'email' => 'Email',
            'address' => 'Адреса',
            'address_ru' => 'Адреса Ru',
            'address_en' => 'Адреса En',
            'link_fb' => 'Посилання Fb',
            'link_linkedin' => 'Посилання Linkedin',
            'link_viber' => 'Посилання Viber',
            'link_insta' => 'Посилання Instagram',
            'link_mail' => 'Посилання Mail',
            'mobile_1' => 'Моб. Телефон',
            'mobile_2' => 'Моб. Телефон',
            'mobile_3' => 'Моб. Телефон',
        ];
    }

    public static function getContact(){
      return self::findOne(1);
    }

    public function afterFind()
    {
        if(Yii::$app->language=='ru'){
            $this->address = $this->address_ru;
        }

        if(Yii::$app->language=='en'){
            $this->address = $this->address_en;
        }
        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}
