<?php

namespace backend\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "file".
 *
 * @property integer $id
 * @property string $file
 * @property string $title
 */
class File extends FileUpload
{

    public $deleting;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'file';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['file', 'file'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'file' => 'Файл',
            'title' => 'Описание файла',
            'id' => 'ID',
        ];
    }

    public function afterFind()
    {
        $this->title = json_decode($this->title, 1);

        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->title = json_encode($this->title);

        $this->file = UploadedFile::getInstance($this, 'file');

        if($this->file){
            $name =  $this->generateName() . '.' . $this->file->extension;
            $this->file->saveAs(Yii::getAlias("@frontend").'/web/images/' .$name);
            $this->file = $name;
        }elseif($this->oldAttributes['file'] && !$this->deleting){
            $this->file = $this->oldAttributes['file'];
        }
        Yii::$app->cacheFrontend->delete('files');


        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
