<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "message".
 *
 * @property integer $id
 * @property string $message
 */
class Message extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'message';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pages'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'message' => 'Текст',
            'pages' => 'Страница или блок',
        ];
    }

    public function afterFind()
    {
        $this->message = json_decode($this->message, 1);

        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->message = json_encode($this->message);
        Yii::$app->cacheFrontend->delete('messages');



            $cache = Yii::$app->cache;
            $key = "update_time";
            $cache->set($key, time());



        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
