<?php

namespace backend\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "og".
 *
 * @property integer $id
 * @property string $title
 * @property string $title_ru
 * @property string $title_en
 * @property string $description
 * @property string $description_ru
 * @property string $description_en
 * @property string $images
 */
class Og extends FileUpload
{

    public $imagePreview;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'og';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['imagePreview'], 'file', 'extensions' => 'png, jpg'],
            [['description', 'description_ru', 'description_en'], 'string'],
            [['title', 'title_ru', 'title_en'], 'string', 'max' => 500],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'title_ru' => 'Title Ru',
            'title_en' => 'Title En',
            'description' => 'Description',
            'description_ru' => 'Description Ru',
            'description_en' => 'Description En',
            'imagePreview' => 'Картинка',
        ];
    }

    public function beforeSave($insert)
    {
        $this->imagePreview = UploadedFile::getInstance($this, 'imagePreview');

        if($this->images==null){
            $this->images = [
                "imagePreview"=>""
            ];
            $this->images = json_encode($this->images);
            $this->images = json_decode($this->images);
        }

        if($this->imagePreview){
            $name =  $this->generateName() . '.' . $this->imagePreview->extension;
            $this->imagePreview->saveAs(Yii::getAlias("@frontend").'/web/images/' .$name);
            $this->images->imagePreview = $name;
        }
        $this->images = json_encode($this->images);



            $cache = Yii::$app->cache;
            $key = "update_time";
            $cache->set($key, time());


        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $this->images = json_decode($this->images);

        if(Yii::$app->language=='ru'){
            $this->title = $this->title_ru;
            $this->description = $this->description_ru;
        }

        if(Yii::$app->language=='en'){
            $this->title = $this->title_en;
            $this->description = $this->description_en;
        }

        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}
