<?php

namespace backend\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "reviews".
 *
 * @property integer $id
 * @property string $name
 * @property string $name_ru
 * @property string $name_en
 * @property string $role
 * @property string $role_ru
 * @property string $role_en
 * @property string $message
 * @property string $message_ru
 * @property string $message_en
 * @property string $images
 */
class Reviews extends FileUpload
{
    public $imagePreview;
    public $avatar;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'reviews';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['imagePreview','avatar'], 'file', 'extensions' => 'png, jpg'],
            [['message', 'message_ru', 'message_en'], 'string'],
            [['project_id','name', 'name_ru', 'name_en', 'role', 'role_ru', 'role_en'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Ім\'я',
            'name_ru' => 'Ім\'я Ru',
            'name_en' => 'Ім\'я En',
            'role' => 'Опис',
            'role_ru' => 'Опис Ru',
            'role_en' => 'Опис En',
            'message' => 'Відгук',
            'message_ru' => 'Відгук Ru',
            'message_en' => 'Відгук En',
            'imagePreview' => 'Фон (Рекомендований розмір [568x420])',
            'avatar' => 'Аватар (Рекомендований розмір [158x149])',
            'project_id' => 'Зв\'язати з сторінкою проекта:',
        ];
    }

    public function beforeSave($insert)
    {


        $this->imagePreview = UploadedFile::getInstance($this, 'imagePreview');
        $this->avatar = UploadedFile::getInstance($this, 'avatar');

        if($this->images==null){
            $this->images = [
                "imagePreview"=>"",
                "avatar"=>""
            ];
            $this->images = json_encode($this->images);
            $this->images = json_decode($this->images);
        }

        if($this->imagePreview){
            $name =  $this->generateName() . '.' . $this->imagePreview->extension;
            $this->imagePreview->saveAs(Yii::getAlias("@frontend").'/web/images/' .$name);
            $this->images->imagePreview = $name;
        }

        if($this->avatar){
            $name =  $this->generateName() . '.' . $this->avatar->extension;
            $this->avatar->saveAs(Yii::getAlias("@frontend").'/web/images/' .$name);
            $this->images->avatar = $name;
        }

        $this->images = json_encode($this->images);



            $cache = Yii::$app->cache;
            $key = "update_time";
            $cache->set($key, time());


        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $this->images = json_decode($this->images);

        if(Yii::$app->language=='ru'){
            $this->name = $this->name_ru;
            $this->role = $this->role_ru;
            $this->message = $this->message_ru;
        }

        if(Yii::$app->language=='en'){
            $this->name = $this->name_en;
            $this->role = $this->role_en;
            $this->message = $this->message_en;
        }

        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public static function getReviews()
    {
        return self::find()->all();
    }
}
