<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "seo".
 *
 * @property integer $id
 * @property string $name_page
 * @property string $sumbol_id
 * @property string $title
 * @property string $description
 */
class Seo extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'seo';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'description'], 'string'],
            [['name_page', 'sumbol_id'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name_page' => 'Название страницы',
            'sumbol_id' => 'Sumbol ID',
            'title' => 'Title',
            'description' => 'Description',
        ];
    }

    public function afterFind()
    {


        $this->title = json_decode(json_decode($this->title),true);
        $this->description = json_decode(json_decode($this->description),true);
        parent::afterFind(); // TODO: Change the autogenerated stub

    }

    public function beforeSave($insert)
    {
        $this->title = json_encode($this->title);
        $this->description = json_encode($this->description);
        Yii::$app->cacheFrontend->delete('title');
        Yii::$app->cacheFrontend->delete('description');

            $cache = Yii::$app->cache;
            $key = "update_time";
            $cache->set($key, time());

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
